# Generated by Django 5.2.5 on 2025-09-02 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clustering", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("UNCERTAIN", "Uncertain"),
                            ("DELETION", "Deletion"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("source_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="observations/%Y/%m/%d/",
                    ),
                ),
                ("interest_reason", models.TextField(max_length=500)),
                ("tags", models.CharField(blank=True, max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clusters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="observations",
                        to="clustering.cluster",
                    ),
                ),
            ],
        ),
    ]
