# Generated by Django 5.2.5 on 2025-09-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("observations", "0001_initial"),
        ("scan_periods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("motivation", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code, e.g., #FFFFFF", max_length=7
                    ),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="proposals",
                        to="observations.observation",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="scan_periods.period",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefiningForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defining_forces",
                        to="scan_periods.period",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("motivation", models.TextField(blank=True)),
                ("robustness_score", models.PositiveIntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code, e.g., #FFFFFF", max_length=7
                    ),
                ),
                (
                    "defining_forces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="final_clusters",
                        to="clustering.definingforce",
                    ),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="final_clusters",
                        to="observations.observation",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_clusters",
                        to="scan_periods.period",
                    ),
                ),
            ],
        ),
    ]
